### ISSUE TITLE
Giving error while executing command - 'denovamon start --command="deno run --allow-net --allow-read --allow-write --allow-plugin --allow-env main.ts"'

### ISSUE THREAD

**Issue by ashokbuxar** [viandwi24/denovamon#1]
First I installed denovamon. when I try to run command - denovamon start --command="deno run --allow-net --allow-read --allow-write --allow-plugin --allow-env main.ts", It gives following error - 
error: Uncaught TypeError: Deno.openPlugin is not a function
  return Deno.openPlugin(localPath);        
              ^
    at prepare (https://deno.land/x/plugin_prepare@v0.6.0/mod.ts:64:15)
    at async init (https://deno.land/x/mongo@v0.7.0/ts/util.ts:41:3)
    at async https://deno.land/x/mongo@v0.7.0/mod.ts:13:1

How to solve this.

**Comment by viandwi24** [comment]
thank you for the report, i will check it further.
