### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by hom-bahrani** [viandwi24/denovamon#2]
Thanks for setting up this project, it would be awesome to have a nodemon alternative with Deno. When I try to run this programmatically in my project via `deno run --allow-read --allow-run denovamon.ts` it start up ok, but then if I make any change to my `mod.ts` file I get this error complaining about the port already being used.

```bash
error: Uncaught AddrInUse: Address already in use (os error 48)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at Object.listen ($deno$/ops/net.ts:51:10)
    at Object.listen ($deno$/net.ts:155:22)
    at Application.serve (https://deno.land/std@0.58.0/http/server.ts:256:25)
    at Application.listen (https://deno.land/x/oak/application.ts:348:20)
    at file:///Users/hombahrani/Code/deno/Deno-Kubernetes-DynamoDB/src/auth/mod.ts:37:11
    at <anonymous> (<anonymous>)
```

**Comment by viandwi24** [comment]
Well, I'm sorry for this. it looks like denovamon failed to do its job, he
didn't stop the previous process and immediately restarted the server which
caused the previous port to crash

thank you for the report, i will check it further.
